// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: configs.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CfgPrize struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Prize []int32  `protobuf:"varint,2,rep,packed,name=Prize,proto3" json:"Prize,omitempty"`
	Item  *ItemCnt `protobuf:"bytes,3,opt,name=Item,proto3" json:"Item,omitempty"`
}

func (x *CfgPrize) Reset() {
	*x = CfgPrize{}
	if protoimpl.UnsafeEnabled {
		mi := &file_configs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CfgPrize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CfgPrize) ProtoMessage() {}

func (x *CfgPrize) ProtoReflect() protoreflect.Message {
	mi := &file_configs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CfgPrize.ProtoReflect.Descriptor instead.
func (*CfgPrize) Descriptor() ([]byte, []int) {
	return file_configs_proto_rawDescGZIP(), []int{0}
}

func (x *CfgPrize) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CfgPrize) GetPrize() []int32 {
	if x != nil {
		return x.Prize
	}
	return nil
}

func (x *CfgPrize) GetItem() *ItemCnt {
	if x != nil {
		return x.Item
	}
	return nil
}

type CfgTest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name  string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Gift  int32    `protobuf:"varint,3,opt,name=Gift,proto3" json:"Gift,omitempty"`
	Prize []int32  `protobuf:"varint,4,rep,packed,name=Prize,proto3" json:"Prize,omitempty"`
	Item  *ItemCnt `protobuf:"bytes,5,opt,name=Item,proto3" json:"Item,omitempty"`
}

func (x *CfgTest) Reset() {
	*x = CfgTest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_configs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CfgTest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CfgTest) ProtoMessage() {}

func (x *CfgTest) ProtoReflect() protoreflect.Message {
	mi := &file_configs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CfgTest.ProtoReflect.Descriptor instead.
func (*CfgTest) Descriptor() ([]byte, []int) {
	return file_configs_proto_rawDescGZIP(), []int{1}
}

func (x *CfgTest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CfgTest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CfgTest) GetGift() int32 {
	if x != nil {
		return x.Gift
	}
	return 0
}

func (x *CfgTest) GetPrize() []int32 {
	if x != nil {
		return x.Prize
	}
	return nil
}

func (x *CfgTest) GetItem() *ItemCnt {
	if x != nil {
		return x.Item
	}
	return nil
}

type Cfg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prize map[string]*CfgPrize `protobuf:"bytes,1,rep,name=Prize,proto3" json:"Prize,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Test  map[string]*CfgTest  `protobuf:"bytes,2,rep,name=Test,proto3" json:"Test,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Cfg) Reset() {
	*x = Cfg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_configs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cfg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cfg) ProtoMessage() {}

func (x *Cfg) ProtoReflect() protoreflect.Message {
	mi := &file_configs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cfg.ProtoReflect.Descriptor instead.
func (*Cfg) Descriptor() ([]byte, []int) {
	return file_configs_proto_rawDescGZIP(), []int{2}
}

func (x *Cfg) GetPrize() map[string]*CfgPrize {
	if x != nil {
		return x.Prize
	}
	return nil
}

func (x *Cfg) GetTest() map[string]*CfgTest {
	if x != nil {
		return x.Test
	}
	return nil
}

var File_configs_proto protoreflect.FileDescriptor

var file_configs_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4e, 0x0a,
	0x08, 0x43, 0x66, 0x67, 0x50, 0x72, 0x69, 0x7a, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x72, 0x69,
	0x7a, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x05, 0x50, 0x72, 0x69, 0x7a, 0x65, 0x12,
	0x1c, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e,
	0x49, 0x74, 0x65, 0x6d, 0x43, 0x6e, 0x74, 0x52, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x22, 0x75, 0x0a,
	0x07, 0x43, 0x66, 0x67, 0x54, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x47, 0x69, 0x66, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x47, 0x69, 0x66, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x50, 0x72, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x03, 0x28, 0x05, 0x52,
	0x05, 0x50, 0x72, 0x69, 0x7a, 0x65, 0x12, 0x1c, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x43, 0x6e, 0x74, 0x52, 0x04,
	0x49, 0x74, 0x65, 0x6d, 0x22, 0xd8, 0x01, 0x0a, 0x03, 0x43, 0x66, 0x67, 0x12, 0x25, 0x0a, 0x05,
	0x50, 0x72, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x43, 0x66,
	0x67, 0x2e, 0x50, 0x72, 0x69, 0x7a, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x50, 0x72,
	0x69, 0x7a, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x54, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x43, 0x66, 0x67, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x04, 0x54, 0x65, 0x73, 0x74, 0x1a, 0x43, 0x0a, 0x0a, 0x50, 0x72, 0x69, 0x7a, 0x65,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1f, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x43, 0x66, 0x67, 0x50, 0x72, 0x69, 0x7a,
	0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x41, 0x0a, 0x09,
	0x54, 0x65, 0x73, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1e, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x43, 0x66, 0x67,
	0x54, 0x65, 0x73, 0x74, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42,
	0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_configs_proto_rawDescOnce sync.Once
	file_configs_proto_rawDescData = file_configs_proto_rawDesc
)

func file_configs_proto_rawDescGZIP() []byte {
	file_configs_proto_rawDescOnce.Do(func() {
		file_configs_proto_rawDescData = protoimpl.X.CompressGZIP(file_configs_proto_rawDescData)
	})
	return file_configs_proto_rawDescData
}

var file_configs_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_configs_proto_goTypes = []interface{}{
	(*CfgPrize)(nil), // 0: CfgPrize
	(*CfgTest)(nil),  // 1: CfgTest
	(*Cfg)(nil),      // 2: Cfg
	nil,              // 3: Cfg.PrizeEntry
	nil,              // 4: Cfg.TestEntry
	(*ItemCnt)(nil),  // 5: ItemCnt
}
var file_configs_proto_depIdxs = []int32{
	5, // 0: CfgPrize.Item:type_name -> ItemCnt
	5, // 1: CfgTest.Item:type_name -> ItemCnt
	3, // 2: Cfg.Prize:type_name -> Cfg.PrizeEntry
	4, // 3: Cfg.Test:type_name -> Cfg.TestEntry
	0, // 4: Cfg.PrizeEntry.value:type_name -> CfgPrize
	1, // 5: Cfg.TestEntry.value:type_name -> CfgTest
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_configs_proto_init() }
func file_configs_proto_init() {
	if File_configs_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_configs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CfgPrize); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_configs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CfgTest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_configs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cfg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_configs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_configs_proto_goTypes,
		DependencyIndexes: file_configs_proto_depIdxs,
		MessageInfos:      file_configs_proto_msgTypes,
	}.Build()
	File_configs_proto = out.File
	file_configs_proto_rawDesc = nil
	file_configs_proto_goTypes = nil
	file_configs_proto_depIdxs = nil
}
